name: Caller Workflow

on: push

jobs:
    call:
        runs-on: ubuntu-latest
        steps:
            - name: sending inputs to the INPUT_reusable.yml file
              uses: ./.github/workflows/INPUTS_reusable.yml
              with:
                message: "Hello from Amogh"

