name: Matrix Demo
on: 
  push:
    paths:
        - '.github/workflows/Matrix.yml'  # So that when changes are done into this file only and than only this workflow will run 
jobs:
    build:
        continue-on-error: true
        strategy:
          matrix: 
            node-version: [12 ,18 ,20]
            os-version: [ubuntu-latest , windows-latest]

            include:
                - node-version: 16
                  os-version: unbuntu-latest
            
            exclude:
                - node-version: 12
                  os-version: windows-latest

        runs-on: ${{ matrix.os-version }}
        steps:
            - name: Get node
              uses: actions/checkout@v4
            - name: Install nodejs
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build Project 
              run: npm run build
