name: output reusable workflow
on:
  workflow_call:
    outputs:
        workflow-output: 
            value: ${{ jobs.job1.outputs.job-output }}

jobs:
  job1:
    outputs:
        job-output: ${{ steps.produce.outputs.step-output }}

    runs-on: ubuntu-latest
    steps:
      - name: Get output
        id: produce
        run: |
          echo "step-output=12" >> $GITHUB_OUTPUT